export default Object.freeze([
    {
        name: 'school 1',
        minGpa: 2.75,
        averageGpa: 3.40,
        dataYear: 2016,
        state: 'California',
        address: '563 Minna Street, San Francisco, ca',
        classSize: 40,
        accredidation: 'probation',
        pacePassPercentage: 100,
        workHours: 2000,
    },
    {
        name: 'school 2',
        minGpa: 3.00,
        averageGpa: 3.55,
        dataYear: 2016,
        state: 'Colorado',
        address: '125 Snow street, Denver, Co',
        classSize: 25,
        accredidation: 'probation',
        pacePassPercentage: 93,
        workHours: 3000,
    },
    {
        name: 'school 3',
        minGpa: 2.75,
        averageGpa: 3.40,
        dataYear: 2016,
        state: 'California',
        address: '1269 Laurel Lane, Lafayette, Ca',
        classSize: 40,
        accredidation: 'probation',
        pacePassPercentage: 100,
        workHours: 0,
    },
    {
        name: 'school 4',
        minGpa: 3.00,
        averageGpa: 3.35,
        dataYear: 2015,
        state: 'Colorado',
        address: '125 Snow street, Boulder, Co',
        classSize: 37,
        accredidation: 'probation',
        pacePassPercentage: 93,
        workHours: 4000,
    },
    {
        name: 'school 5',
        minGpa: 3.2,
        averageGpa: 3.40,
        dataYear: 2016,
        state: 'California',
        address: '842 Folsom Street, San Francisco, Ca',
        classSize: 50,
        accredidation: 'probation',
        pacePassPercentage: 89,
        workHours: 2500,
    },
    {
        name: 'school 6',
        minGpa: 3.00,
        averageGpa: 3.55,
        dataYear: 2016,
        state: 'Colorado',
        address: '125 Snow street, Boulder, Co',
        classSize: 25,
        accredidation: 'probation',
        pacePassPercentage: 98,
        workHours: 1500,
    },
])